stages:
  - buildwebpack
  - builddocker
  - deploy
  - report

job_build_webpack_master:
  stage: buildwebpack
  image: registry.cn-hangzhou.aliyuncs.com/tik/node:tik
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    policy: push
  script:
    - rm -fr node_modules
    - cp .env.example .env
    - tik docker
  only:
    - master
  artifacts:
    name: ${CI_COMMIT_REF_SLUG}
    paths: 
      - dist
      - docker-compose.yml
      - rancher-compose.yml
    expire_in: 10 mins
  variables:
    TIME_STAMP: 1539171419772
    APP_NAME: tikBackWeb
    APP_ID: 1004
    BACK_SYSTEM_URL: http://localhost:3003
    TEST: 1
    NODE_ENV: development


job_build_webpack_release:
  stage: buildwebpack
  image: registry.cn-hangzhou.aliyuncs.com/tik/node:tik
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    policy: push
  script:
    - NODE_ENV=development npm install --registry=https://registry.npm.taobao.org
    - npm run build
    - ls
    - rm -fr node_modules
    - cp .env.example .env
    - tik docker
  only:
    - /^release.*$/
  artifacts:
    name: ${CI_COMMIT_REF_SLUG}
    paths: 
      - dist
    expire_in: 10 mins
  variables:
    TIME_STAMP: 1539171419772
    APP_NAME: tikBackWeb
    APP_ID: 1004
    BACK_SYSTEM_URL: http://localhost:3003
    TEST: 1
    NODE_ENV: production


job_build_docker_master:
  stage: builddocker
  image: gitlab/dind
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
  only:
    - master
  script:
    - docker build -t tibi:stable .
    - docker login --username=tik-admin@tik registry.cn-hangzhou.aliyuncs.com -p g423QuHLvqrRTY37
    - docker tag tibi:stable registry.cn-hangzhou.aliyuncs.com/tik/coin2stock-tibi:stable
    - docker push registry.cn-hangzhou.aliyuncs.com/tik/coin2stock-tibi:stable
    - rm -fr node_modules
  dependencies:
    - job_build_webpack_master  

job_build_docker_release:
  stage: builddocker
  image: gitlab/dind
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
  only:
    - /^release.*$/
  script:
    - docker build -t tibi:1.0.3 .
    - docker login --username=tik-admin@tik registry.cn-hangzhou.aliyuncs.com -p g423QuHLvqrRTY37
    - docker tag tibi:1.0.3 registry.cn-hangzhou.aliyuncs.com/tik/coin2stock-tibi:1.0.3
    - docker push registry.cn-hangzhou.aliyuncs.com/tik/coin2stock-tibi:1.0.3
    - rm -fr node_modules
  dependencies:
    - job_build_webpack_release  

job_deploy:
  stage: deploy
  image: registry.cn-hangzhou.aliyuncs.com/dev_tool/rancher-cli
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
  only:
    - master
  dependencies:
    - job_build_webpack_master
  script:
    - rm -f ~/.rancher/cli.json
    - rm -fr node_modules
    - rancher --url http://172.20.160.7:8080/v2-beta --access-key A7B232C96113121C64A2 --secret-key 8mAJL2iDVr7k5BT7Ws32h41MyfJY1ubWBGBAM8Ub up -d  --pull --force-upgrade --confirm-upgrade --stack coin2stock-tibi
    
job_report:
  stage: report
  image: registry.cn-hangzhou.aliyuncs.com/tik/node:tik
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
  when: on_failure
  script:
    - curl https://oapi.dingtalk.com/robot/send?access_token=4b6c67515042a6f16ff5799eedf77231ccb785cd1842c28c73c2dd8499113d2f -XPOST -H 'content-type:application/json' -d '{"msgtype":"text","text":{"content":"[coin2stock-tibi] Job Failed. Link:http://172.20.160.7:10080/coin2stock/tibi/pipelines"}}'
  
